server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: rm-2ze936157744v8bl59o.mysql.rds.aliyuncs.com/schoolclub
    username: dazao
    password: Asd2003828