server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://rm-2ze936157744v8bl59o.mysql.rds.aliyuncs.com:3306/schoolclub
    username: dazao
    password: Asd2003828
    url: jdbc:mysql://rm-2ze936157744v8bl59o.mysql.rds.aliyuncs.com:3306/schoolclub
  security:
    key: dazaoabc
    expire: 7
    filter:
      order: -100
  data:
    redis:
      database: 8
      password: Asd2003828
      host: r-2zehb42aq37efq775ppd.redis.rds.aliyuncs.com
